# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestSss(object):

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.login()

    def teardown_method(self, method):
        self.driver.quit()

    def login(self):
        self.driver.get("https://passport.jd.com/uc/login?ltype=logout&ReturnUrl=https://item.jd.com/100026667878.html")
        self.driver.find_element(By.ID, "tryBtn").click()
        time.sleep(5)
        self.test_sss()

    def test_sss(self):
        # Test name: sss
        # Step # | name | target | value
        # 1 | open | /100026667878.html |
        # self.driver.get("https://item.jd.com/100026667878.html")
        # self.driver.get("https://marathon.jd.com/seckillnew/orderService/pc/submitOrder.action?skuId=100026667878")
        self.driver.get("https://marathon.jd.com/seckill/seckill.action?skuId=100014366717&num=1&rid=1633426563")
        # 2 | setWindowSize | 922x835 |
        self.driver.set_window_size(1920, 1080)
        # 3 | click | id=btn-reservation |
        self.driver.find_element(By.ID, "btn-reservation").click()
        self.driver.find_element(By.ID, "checkout-submit").click()
        # assert self.driver.switch_to.alert.text == "很遗憾没有抢到，再接再厉哦。"


if __name__ == '__main__':
    t = TestSss()
    while 1:
        t.setup_method(None)
